using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Inventory_UI_with_flower : MonoBehaviour
{
    public GameObject inventoryPanel;
    public Player player;

    void Start()
    {
        inventoryPanel.SetActive(false);
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.B))
        {
            ToggleInventory();
        }
    }

    public void ToggleInventory()
    {
        if (!inventoryPanel.activeSelf)
        {
            inventoryPanel.SetActive(true);
        }
        else
        {
            inventoryPanel.SetActive(false);
        }
    }
}